version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 2000000000000ufia
  mnemonic: random fresh tree moral please become practice hammer hawk spoon coyote shallow art near mention drama bag wonder talk silver thrive effort swear buffalo
- name: bob
  coins:
  - 1000000000000ufia
genesis:
  chain_id: fiamma-testnet-1
  app_state:
    staking:
      params:
        bond_denom: ufia
    gov:
      params:
        min_deposit:
        - amount: "10000000"
          denom: ufia
        expedited_min_deposit:
        - amount: "50000000"
          denom: ufia
    mint:
      params:
        mint_denom: ufia
    crisis:
      constant_fee:
        denom: ufia
        amount: "1000"
    bitvmstaker:
      committee_address: fiamma13k3wqnp4zcrlwtph6xk7l6feunu5ae2k6pqnaw
      staker_addresses: [fiammavaloper13k3wqnp4zcrlwtph6xk7l6feunu5ae2k4lsqwf]
    babylon:
      params:
        babylon_contract_address: fiamma14hj2tavq8fpesdwxxcu44rty3hh90vhujrvcmstl4zr3txmfvw9sgx3jav
        btc_staking_contract_address: fiamma1nc5tatafv6eyq7llkr2gv50ff9e22mnf70qgjlv737ktmt4eswrqyn5sl2
        max_gas_begin_blocker: 500000
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5fia
validators:
- name: alice
  bonded: 1000000000ufia
build:
  main: cmd/fiammad
